name: tracknet_env
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.1
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - catboost=1.2.7
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - decorator=5.1.1
  - expat=2.6.3
  - ffmpeg=5.1.2
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freeglut=3.4.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - getopt-win32=0.1
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - gts=0.7.6
  - harfbuzz=6.0.0
  - icc_rt=2022.1.0
  - icu=70.1
  - idna=3.7
  - imageio=2.33.1
  - imageio-ffmpeg=0.5.1
  - intel-openmp=2023.1.0
  - jasper=2.0.33
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.9.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libgd=2.3.3
  - libglib=2.78.4
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.5
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - moviepy=1.0.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.7.0
  - opencv-python-headless=4.8.1.78
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - pango=1.50.14
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - plotly=5.24.1
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proglog=0.1.9
  - psutil=5.9.0
  - py-cpuinfo=9.0.0
  - py-opencv=4.7.0
  - pybind11-abi=5
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0post0
  - python-graphviz=0.20.1
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.4.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - qt-main=5.15.8
  - requests=2.32.3
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - svt-av1=1.4.1
  - sympy=1.13.2
  - tbb=2021.8.0
  - tenacity=8.2.3
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchvision=0.19.0
  - tqdm=4.66.5
  - typing_extensions=4.11.0
  - tzdata=2024b
  - ucrt=10.0.20348.0
  - ultralytics=8.2.83
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - lapx==0.5.10.post1
      - scenedetect==0.6.1
